### ISSUE TITLE
User Area with IsDefaultAuthSchema: Visual Editor cannot make api requests

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#192]
If you have a custom user area and the `IsDefaultAuthSchema` setting to true, the visual editor is unable to save anything. This is because all api requests now throw an exception because the anti forgery token is not valid:

```
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter:Information: Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
```

The problem is because we are using two different auth schemas on the same page, but the .NET Core antiforgery service doesn't let you specify which one to use when generating the token, so it uses the default schema when we actually need a token for the COF area schema.

**Comment by HeyJoel** [comment]
Fixed
