### ISSUE TITLE
Error when adding or editing an image

### ISSUE THREAD

**Issue by mjsmart** [cofoundry-cms/cofoundry#246]
After upgrading to Cofoundry 0.41 I receive the following error when uploading a new image, or editing an existing one:

Could not load type 'Cofoundry.Core.EntityFramework.ITransactionScopeFactory' from assembly 'Cofoundry.Core, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null'.

``
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext)
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 118
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 100
   at Cofoundry.Web.ApiResponseHelper.RunCommandAsync[TCommand](Controller controller, TCommand command) in C:\projects\cofoundry\src\Cofoundry.Web\Framework\WebApi\ApiResponseHelpers\ApiResponseHelper.cs:line 195
   at Cofoundry.Web.Admin.ImagesApiController.Post(AddImageAssetCommand command, IFormFile file) in C:\projects\cofoundry\src\Cofoundry.Web.Admin\Admin\Api\Images\ImagesApiController.cs:line 81
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\Middleware\AutoUpdateMiddleware.cs:line 78
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)``

**Comment by HeyJoel** [comment]
Hi there, first up I'm wondering if there is a framework/packaging issue. Can you check:

- Have you updated to .NET Core 2.1 (upgrade info [here](https://www.cofoundry.org/blog/17/cofoundry-04-released-net-core-21-copy-custom-entities-and-more))
- Are all your projects targeting the same version of Cofoundry
- Have you removed the version number on the package reference to `Microsoft.AspNetCore.App`

Here is a sample project file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cofoundry.Plugins.ErrorLogging.Admin" Version="0.4.0" />
    <PackageReference Include="Cofoundry.Plugins.Imaging.ImageSharp" Version="0.1.0-ci0015" />
    <PackageReference Include="Cofoundry.Plugins.SiteMap" Version="0.4.1" />
    <PackageReference Include="Cofoundry.Web.Admin" Version="0.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

In my test projects I'm not seeing any issues with adding or updating images. What platform are you running on?

**Comment by mjsmart** [comment]
- I've upgraded to .NET Core 2.1
- All projects are targeting the same version of Cofoundry
- I've removed the version number on the package reference for ``Microsoft.AspNetCore.App``

The only difference in my project file is in my ``Cofoundry.Plugins.Imaging.ImageSharp`` version. I was on ``0.1.0-ci0013``, and after upgrading to ``0.1.0-ci0015`` the issue has gone away.

**Comment by HeyJoel** [comment]
The ImageSharp package is a bit different to the other packages since ImageSharp is still in pre-release and so it doesn't follow the same versioning pattern as the other Cofoundry components. `0.1.0-ci0013` is referencing Cofoundry 0.3.2 which doesn't contain the new `ITransactionScopeFactory`.

I'm looking forward to a final release of ImageSharp, hopefully it will come soon!
