### ISSUE TITLE
Cofoundry.Web.StaticFilePathFormatter.AppendVersion(string applicationRelativePath)

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#269]
Hi,
I've been working with cofoundry for a while with no problems. I just created a new project today and I'm getting the following error when I try to run the project:

`System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.TagHelpers.Internal.FileVersionProvider' from assembly 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

   at Cofoundry.Web.StaticFilePathFormatter.AppendVersion(String applicationRelativePath)

   at Cofoundry.Web.Admin.StaticResourceReferenceRenderer.CssPath(ModuleRouteLibrary moduleRouteLibrary, String fileName) in C:\projects\cofoundry\src\Cofoundry.Web.Admin\Framework\UI\StaticResourceReferenceRenderer.cs:line 60

   at Cofoundry.Web.Admin.StaticResourceReferenceRenderer.CssTag(ModuleRouteLibrary moduleRouteLibrary, String fileName) in C:\projects\cofoundry\src\Cofoundry.Web.Admin\Framework\UI\StaticResourceReferenceRenderer.cs:line 126

   at AspNetCore._Admin_Modules_Shared_MVC_Views_Layouts__BaseLayout.<>c__DisplayClass8_0.<<ExecuteAsync>b__0>d.MoveNext() in /Admin/Modules/Shared/MVC/Views/Layouts/_BaseLayout.cshtml:line 32

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()

   at AspNetCore._Admin_Modules_Shared_MVC_Views_Layouts__BaseLayout.ExecuteAsync() in /Admin/Modules/Shared/MVC/Views/Layouts/_BaseLayout.cshtml:line 15

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)

   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\Middleware\AutoUpdateMiddleware.cs:line 78

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by endrehegyi** [comment]
I tested it again, I created a project in VS code using: dotnet new mvc, then I do all the Cofoundry installation steps, When I try to run the project it navigates to the /admin page but it throws that error.

**Comment by endrehegyi** [comment]
The problem seems to be from using the latest .net core preview SDK version (v2.2.0-preview3) after going back to 2.1.403 the problem has gone away. 

I completely forgot about installing the preview SDK version.

**Comment by HeyJoel** [comment]
I'm not sure what the bahaviour should be with the preview versions but it looks like a package mismatch issue. Generally i would have expected it to work but maybe there's a breaking change in 2.2 with something we're using.
