### ISSUE TITLE
Custom entity admin module editor error

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#307]
Hi, 
we create a custom entity with 4 fields and all was be correct, but later we add new fields. Now we can't acces to custom entity admin panel module to edit these custom entities. When we try to open custom entities editor we gets the next error.

Can you help me?

![image](https://user-images.githubusercontent.com/8802992/55553776-6bef8380-56e1-11e9-8c56-765c4c324853.png)

```
EntityNotFoundException`1: Entity of type 'Cofoundry.Domain.ICustomEntityDefinition' and identifier 'simcom' could not be found.
Cofoundry.Domain.SearchCustomEntitySummariesQueryHandler.GetPermissions(SearchCustomEntitySummariesQuery query)+MoveNext()
Cofoundry.Domain.PermissionValidationService.EnforcePermission(IEnumerable<IPermissionApplication> permissions, IUserContext userContext) in PermissionValidationService.cs
Cofoundry.Domain.ExecutePermissionValidationService.Validate<TQuery, TResult>(TQuery query, IAsyncQueryHandler<TQuery, TResult> queryHandler, IExecutionContext executionContext) in ExecutePermissionValidationService.cs
Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync<TQuery, TResult>(TQuery query, IExecutionContext executionContext) in QueryExecutor.cs
Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync<TResult>(IQuery<TResult> query, IExecutionContext executionContext)
Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync<TResult>(IQuery<TResult> query)
Cofoundry.Web.Admin.CustomEntityDefinitionsApiController.GetCustomEntities(string customEntityDefinitionCode, SearchCustomEntitySummariesQuery query) in CustomEntityDefinitionsApiController.cs
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in AutoUpdateMiddleware.cs
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
Cofoundry.Core.EntityNotFoundException`1[Cofoundry.Domain.ICustomEntityDefinition]: Entity of type 'Cofoundry.Domain.ICustomEntityDefinition' and identifier 'simcom' could not be found.
   at Cofoundry.Domain.SearchCustomEntitySummariesQueryHandler.GetPermissions(SearchCustomEntitySummariesQuery query)+MoveNext()
   at Cofoundry.Domain.PermissionValidationService.EnforcePermission(IEnumerable`1 permissions, IUserContext userContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\Roles\Services\PermissionValidationService.cs:line 270
   at Cofoundry.Domain.ExecutePermissionValidationService.Validate[TQuery,TResult](TQuery query, IAsyncQueryHandler`2 queryHandler, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\Roles\Services\ExecutePermissionValidationService.cs:line 51
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync[TQuery,TResult](TQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Query\QueryExecutor.cs:line 97
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query, IExecutionContext executionContext)
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query)
   at Cofoundry.Web.Admin.CustomEntityDefinitionsApiController.GetCustomEntities(String customEntityDefinitionCode, SearchCustomEntitySummariesQuery query) in C:\projects\cofoundry\src\Cofoundry.Web.Admin\Admin\Api\CustomEntities\CustomEntityDefinitionsApiController.cs:line 62
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateMiddleware.cs:line 46
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by HeyJoel** [comment]
So the error is that the custom entity definition for entity code **simcom** could not be found. In these new properties are you referencing the simcom custom entity type? By convention I use upper case for definition codes, are you using the correct casing in the code reference?

**Comment by HeyJoel** [comment]
Some other things to think about:

- Did the custom entity definition code change (e.g. from lower to upper case)? This should not be changed once set.
- Since changing the definitions have you re-built the project and refreshed the admin page? It looks like the sort of error you would get if the custom entity definition was removed or the code was changed but you hadn't refreshed the admin panel page (i.e. it was still referencing an old code).

**Comment by HeyJoel** [comment]
Closing due to inactivity
