### ISSUE TITLE
Database Locked Exception 

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#324]
Hi 
I get this error when running one of my projects that have been working fine before. 

```
Cofoundry.Core.AutoUpdate.DatabaseLockedException: The database has been locked to prevent accidental automatic updates. Please unlock it before pushing updates.
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.UpdateAsync() in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 94
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\Middleware\AutoUpdateMiddleware.cs:line 56
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Does anyone know how to fix this?

**Comment by mcockrellsana** [comment]
You likely stopped the process while it was loading up or encountered an error on start up and then stopped the debugger, etc.  

This is a process that Cofoundry takes when start up occurs where it checks interfaces and does reflection esque activities to make sure data models are up to date (with custom entities, etc).  The auto update process puts values in two tables: Cofoundry.AutoUpdateLock and Cofoundry.DistributedLock.

Before you restart your application, make sure that the value in AutoUpdateLock is set to 0 and you can just DELETE FROM or TRUNCATE the DistributedLock table rows.  This will free up the application on next start up to do it's process.  As i've seen it will recreate the rows in DistrubutedLock that you've deleted, but will null values, which means the system is not locked.

Joel can provide more information that I may have missed or have wrong, but this has always worked for me when this occurs.

**Comment by HeyJoel** [comment]
@mcockrellsana is correct, a full explaination of this process and how to remove the temporary lock can be found on issue #282.

I'd like to somehow automatically disable the locking process when debugging locally, but I don't really like the idea of having the process run differently for development than production. 

What we could do is improve the error detail and look into displaying a different error page when in development mode that gives you the option to clear the lock.

**Comment by endrehegyi** [comment]
Thank you @mcockrellsana , that has solved the problem.
