### ISSUE TITLE
Cofoundry.Domain.PermissionValidationFailedException: Permission Validation Check Failed

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#340]
Hi,
  I tried get Customenity data but I got this error.

Note:
1. That api working postman but I tried access that api ajax call I got this error can you help me on this.

Cofoundry.Domain.PermissionValidationFailedException: Permission Validation Check Failed. Permission Type: Cofoundry.Domain.CustomEntityReadPermission. UserId: 
   at Cofoundry.Domain.PermissionValidationService.EnforcePermission(IPermissionApplication permission, IUserContext userContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\Roles\Services\PermissionValidationService.cs:line 243
   at Cofoundry.Domain.PermissionValidationService.EnforcePermission(IEnumerable`1 permissions, IUserContext userContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\Roles\Services\PermissionValidationService.cs:line 270
   at Cofoundry.Domain.ExecutePermissionValidationService.Validate[TQuery,TResult](TQuery query, IAsyncQueryHandler`2 queryHandler, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\Roles\Services\ExecutePermissionValidationService.cs:line 51
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync[TQuery,TResult](TQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Query\QueryExecutor.cs:line 97
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query, IExecutionContext executionContext)
   at Po.model.Query.GetGuQueryHandler.BuildAsync(PagedQueryResult`1 customEntityResult) in C:\Users\user2\Desktop\Po\Po\model\Query\GetGuQueryHandler.cs:line 127
   at Po.model.Query.GetGuQueryHandler.ExecuteAsync(GetGuQuery query, IExecutionContext executionContext) in C:\Users\user2\Desktop\Po\Po\model\Query\GetGuQueryHandler.cs:line 46
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync[TQuery,TResult](TQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Query\QueryExecutor.cs:line 97
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query, IExecutionContext executionContext)
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query)
   at Po.ApiController.GuController.Get(GetGuQuery query) in C:\Users\user2\Desktop\Pod\ApiController\GuController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateMiddleware.cs:line 46
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 802.1102ms 500 text/html; charset=utf-8

**Comment by ramkrish3020** [comment]
I fixed this issue go admin panel role and permission and edit anonymous role check out the particular custom enity it's working.
Thanks
