### ISSUE TITLE
Exception on running sample site solution

### ISSUE THREAD

**Issue by alishajain7** [cofoundry-cms/cofoundry#369]
I am receiving below error on unning the Sample SPA site solution:
Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in AutoUpdateMiddleware.cs, line 49

It says teh site is udpating and trya gin later. After few seconds, the exception details is seen on the screen.

System.Exception: An error has occured while updating the system. See the logs for more details.
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateMiddleware.cs:line 49
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by alishajain7** [comment]
It worked after updating the packages. Thanks.
