### ISSUE TITLE
Error loading page template detail page

### ISSUE THREAD

**Issue by prodigy1** [cofoundry-cms/cofoundry#383]
### Description

Immediately after installing the cofoundry-web template (dotnet new) and clicking through the page, I received an exception.

**Steps to reproduce**
- Install using dotnet-new cofoundry-web
- Setup database, change config, start website
- Configure basic setup
- Navigate to settings->page templates
- Click on the existing "Generic" page template

**Expected behaviour**
- The detail page opens and shows what lies beyond

**Actual behaviour**
- An error occurs, see below

### Environment
- Windows 10 Pro
- SQL Server Developer Edition (15.0.2070.41)
- .NET Core 3.1
- Visual Studio 2019
- IIS Express

```
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (6ms) [Parameters=[@__query_PageTemplateId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)
FROM (
    SELECT [p].[PageVersionId], [p].[CreateDate], [p].[CreatorId], [p].[DisplayVersion], [p].[ExcludeFromSitemap], [p].[MetaDescription], [p].[OpenGraphDescription], [p].[OpenGraphImageId], [p].[OpenGraphTitle], [p].[PageId], [p].[PageTemplateId], [p].[Title], [p].[WorkFlowStatusId]
    FROM [Cofoundry].[PageVersion] AS [p]
    WHERE [p].[PageTemplateId] = @__query_PageTemplateId_0
    GROUP BY [p].[PageId]
) AS [t]
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'Cofoundry.Domain.Data.CofoundryDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Die Cofoundry.PageVersion.PageVersionId-Spalte ist in der Auswahlliste ungültig, da sie nicht in einer Aggregatfunktion und nicht in der GROUP BY-Klausel enthalten ist.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:1e8850cd-cabf-4983-9c93-07cbfb11b104
Error Number:8120,State:1,Class:16
```
![image](https://user-images.githubusercontent.com/344148/96695063-80f63b00-1389-11eb-91da-fba1428af8c4.png)

**Comment by HeyJoel** [comment]
Thanks for the excellent bug report, much appreciated. 

This has been fixed and will be included in the next release (0.8). If you need the fix now you can get the update from our [MyGet feed](https://myget.org/gallery/cofoundry). There's only minor breaking changes, mainly with namespacing of things that most people won't use.
