### ISSUE TITLE
Cofoundry.Web.Admin.Internal.VisualEditorActionResult.ExecuteResultAsync fails with "Synchronous operations are disallowed"

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#401]
I have just installed Cofoundry via "dotnet new cofoundry-web -n Demo" and started the admin website. That runs fine. But when I view the generated pages I randomly get "HTTP2 protocol error" as a result.

I found what I believe is the relevant log-entry in the admin-log section:

Stack Trace
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Cofoundry.Web.Admin.Internal.VisualEditorActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggi

**Comment by JornWildt** [comment]
A workaround is to add `options.AllowSynchronousIO = true`:

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureKestrel((context, options) =>
                {
                    options.AllowSynchronousIO = true;
                });

**Comment by HeyJoel** [comment]
Thanks @JornWildt, this issue doesn't seem to occur when hosting through IIS, I replicated it by using Kestral directly.  I've fixed the bug, but I'll have to wait until later tonight to publish a proper release. For now you can either use the workaround described or use the pre-release package [0.9.1-ci0001](https://myget.org/feed/cofoundry/package/nuget/Cofoundry.Web.Admin/0.9.1-ci0001) on our myget feed.

The issue was where we were disposing of a `StreamWriter`, even though the buffer is flushed/emptied with `FlushAsync()`, it still calls sync `Flush()` when it disposes, which throws the error.
