### ISSUE TITLE
View File Not Found if deployed on Docker

### ISSUE THREAD

**Issue by amitavayourflow** [cofoundry-cms/cofoundry#540]
Hi, 
If anyone can suggest why after publishing with dotnet CLI for docker, 
creates no _xxxx.cshtml.

Below is the docker log
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
2023-06-13 08:58:39       An unhandled exception has occurred while executing the request.
2023-06-13 08:58:39       System.IO.FileNotFoundException: The file /Views/shared/_SideNav.cshtml does not exist.
2023-06-13 08:58:39          at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
2023-06-13 08:58:39          at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.FileProviderRazorProjectItem.Read()
2023-06-13 08:58:39          at Microsoft.AspNetCore.Razor.Language.RazorSourceDocument.ReadFrom(RazorProjectItem projectItem)
2023-06-13 08:58:39          at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.CreateCodeDocumentCore(RazorProjectItem projectItem, Action`1 configureParser, Action`1 configureCodeGeneration)
2023-06-13 08:58:39          at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.CreateCodeDocumentCore(RazorProjectItem projectItem)
2023-06-13 08:58:39          at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
2023-06-13 08:58:39          at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
2023-06-13 08:58:39          at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
2023-06-13 08:58:39       --- End of stack trace from previous location ---

**Comment by HeyJoel** [comment]
Hi there, I'd need more information about where these dashboard pages are localed e.g. are they html files in the wwwroot? Or MVC views/pages etc? Are the files copied into your docker container?

ASP.NET core will not copy view files by default, see [deployment docs](https://www.cofoundry.org/docs/getting-started/publishing-and-deployment) for info on the project settings you need to configure to allow that.
